environment:
  PROJECT_NAME: wintray
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

configuration: Release

platform: Any CPU

before_build:
  - nuget restore

build:
  project: FreenetTray.sln

before_deploy:
  - cd bin\Release
  - 7z a ../%PROJECT_NAME%-%APPVEYOR_REPO_TAG_NAME%.zip FreenetTray.exe FreenetTray.exe.config
  - appveyor PushArtifact ../%PROJECT_NAME%-%APPVEYOR_REPO_TAG_NAME%.zip

deploy:
  description: 'wintray'
  artifact: /.*\.zip/
  #  To change this token:
  #
  # - Go to 'https://github.com/settings/tokens/new' and generate a Token with only the `public_repo` scope enabled
  # - Go to 'https://ci.appveyor.com/tools/encrypt', log in, and paste the token
  # - Replace the "value" below
  auth_token:
    secure: Eyt7YsHauCv2tX8PfbrAP1D5bVauUO9qMGqkfLe9FM3X5l/EjnZ4NBp4oKooz8A1
  provider: GitHub
  on:
    appveyor_repo_tag: true

branches:
  only:
    - master
    - fix-64
    # IMPORTANT Regex to match tags. Required, or appveyor may not trigger deploys when a new tag
    # is pushed. This regex matches semantic versions like v1.2.3-rc4+2016.02.22
    - /^v\d+\.\d+\.\d+.*$/

